# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: db951da7d7928a1750d0edd588aa4f351d7a54709ea82b109d23fdebb835877ea747a3b4505ee7e702260044863fa2188b78936e722b283d515e4c4902b7107d

test:
  secret_key_base: adceb29818d1564ef795d7cb4c0bb252417668e9c9ca7961c77f8eae57f5967e6852873136a2fb017ab09ffeaf4657b18e33407f28172e18aa6e47b00059120a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
